# This file is part of the qt-classic-styles Project.
# License: LGPL-2.1-or-later. Contact: qt-classic-styles-project@trinity2k.net
#
"""Generates the Photon Aurorae window decoration for KWin.

The frame pieces and button cells are cut from the lossless QNX 6.2.1 file
manager screenshot (reference/qnx-photon/qnx621fileman.png) and written as
pixel-aligned SVG rects. Inactive, pressed and deactivated variants are
derived by the colour rules below.

Usage: make_photon_aurorae.py --out DIR [--reference DIR]
"""
from __future__ import annotations

import argparse
import os
import sys
import tempfile

# ElementTree only ever parses SVG this module wrote itself (svg_for).
import xml.etree.ElementTree as ET  # nosec B405
from dataclasses import dataclass
from pathlib import Path

from PIL import Image

Pixel = tuple[int, int, int]
Grid = list[list[Pixel]]

SOURCE = "qnx621fileman.png"
THEME_NAME = "Photon"


@dataclass(frozen=True, slots=True)
class Piece:
    element: str
    source: str
    box: tuple[int, int, int, int]  # left, top, right, bottom; right/bottom exclusive


# The file manager window spans x 0..609 and y 0..435. The title band is rows
# 0..20 (black, #3F3F3F, then 19 rows of title); the frame bands are 5 px.
ACTIVE_FRAME: tuple[Piece, ...] = (
    Piece("decoration-topleft", SOURCE, (0, 0, 5, 21)),
    Piece("decoration-top", SOURCE, (150, 0, 151, 21)),
    Piece("decoration-topright", SOURCE, (605, 0, 610, 21)),
    Piece("decoration-left", SOURCE, (0, 200, 5, 201)),
    Piece("decoration-right", SOURCE, (605, 200, 610, 201)),
    Piece("decoration-bottomleft", SOURCE, (0, 431, 5, 436)),
    Piece("decoration-bottom", SOURCE, (100, 431, 101, 436)),
    Piece("decoration-bottomright", SOURCE, (605, 431, 610, 436)),
)
MAXIMIZED_TITLE = Piece("decoration-maximized-center", SOURCE, (150, 2, 151, 21))

# Right button panel, rows 2..20. Minimize carries the panel's left lip, close
# the etched gap before it and the panel face up to the frame; Aurorae in
# KWin 6.3 has no element for a button group background.
BUTTON_CELLS: tuple[Piece, ...] = (
    Piece("minimize", SOURCE, (543, 2, 565, 21)),
    Piece("maximize", SOURCE, (565, 2, 580, 21)),
    Piece("restore", SOURCE, (565, 2, 580, 21)),
    Piece("close", SOURCE, (580, 2, 605, 21)),
)

WINDOW_FILL: Pixel = (0xD8, 0xD8, 0xD8)

# Inactive title, measured on the inactive calculator in qnx621calc.png.
INACTIVE_BY_VALUE: dict[Pixel, Pixel] = {
    (0x8E, 0xBD, 0xFF): (0xE3, 0xF3, 0xFF),
    (0x5C, 0x8B, 0xDF): (0xB1, 0xC1, 0xD9),
    (0x5D, 0x8C, 0xE0): (0xB1, 0xC1, 0xD9),
    (0x2A, 0x59, 0xAD): (0x7F, 0x8F, 0xA7),
}
INACTIVE_RAMP_START: Pixel = (0xB7, 0xC7, 0xDF)
INACTIVE_RAMP_STEP = -3
TITLE_RAMP_ROWS = range(6, 20)
TITLE_ROW_COLOURS: dict[int, Pixel] = {
    2: (0xE3, 0xF3, 0xFF),
    3: (0xB1, 0xC1, 0xD9),
    4: (0x7F, 0x8F, 0xA7),
    5: (0xB1, 0xC1, 0xD9),
    20: (0x7F, 0x8F, 0xA7),
}

# The capture has a few title pixels with red and blue swapped (#AD592A for
# #2A59AD), a byte-order artifact rather than part of the Photon look.
SWAPPED_CHANNEL_REPAIRS: dict[Pixel, Pixel] = {(0xAD, 0x59, 0x2A): (0x2A, 0x59, 0xAD)}

PRESSED_SHIFT = -24
DEACTIVATED_GLYPH: Pixel = (0x9D, 0x9D, 0x9D)
DARK_LIMIT = 0x48
BUTTON_SIDE = 13

RC_TEXT = """\
# This file is part of the qt-classic-styles Project.
# License: LGPL-2.1-or-later. Contact: qt-classic-styles-project@trinity2k.net
#
# Generated by make_photon_aurorae.py; edit the generator, not this file.

[General]
TitleAlignment=Center
TitleVerticalAlignment=Center
Animation=0
ActiveTextColor=0,0,101,255
InactiveTextColor=63,72,96,255
Shadow=false

[Layout]
BorderLeft=5
BorderRight=5
BorderBottom=5
TitleEdgeTop=2
TitleEdgeBottom=0
TitleEdgeLeft=5
TitleEdgeRight=5
TitleEdgeTopMaximized=0
TitleEdgeBottomMaximized=0
TitleEdgeLeftMaximized=0
TitleEdgeRightMaximized=0
TitleBorderLeft=4
TitleBorderRight=4
TitleHeight=19
ButtonWidth=15
ButtonWidthMinimize=22
ButtonWidthMaximizeRestore=15
ButtonWidthClose=25
ButtonWidthMenu=13
ButtonHeight=19
ButtonSpacing=0
ButtonMarginTop=0
ExplicitButtonSpacer=8
PaddingTop=0
PaddingBottom=0
PaddingLeft=0
PaddingRight=0
"""

METADATA_TEXT = """\
# This file is part of the qt-classic-styles Project.
# License: LGPL-2.1-or-later. Contact: qt-classic-styles-project@trinity2k.net
#
[Desktop Entry]
Name=Photon
Comment=QNX 6 Photon microGUI title bars, to go with the photon widget style
X-KDE-PluginInfo-Author=qt-classic-styles project
X-KDE-PluginInfo-Email=qt-classic-styles-project@trinity2k.net
X-KDE-PluginInfo-Name=Photon
X-KDE-PluginInfo-Version=0.1
X-KDE-PluginInfo-License=LGPL-2.1-or-later
X-KDE-PluginInfo-EnabledByDefault=true
"""


def repaired(grid: Grid) -> Grid:
    return [[SWAPPED_CHANNEL_REPAIRS.get(p, p) for p in row] for row in grid]


def bevel_corner(vertical_band: list[Pixel], horizontal_band: list[Pixel]) -> Grid:
    """Bottom-right corner joining the right band (left to right) and the
    bottom band (top to bottom); each pixel takes the band it is deeper in.

    Photon draws a blue resize grip here that a fixed 5 px corner cannot hold.
    """
    size = len(vertical_band)
    if size != len(horizontal_band) or size == 0:
        raise ValueError("bands must have the same, non-zero width")
    return [[vertical_band[x] if x >= y else horizontal_band[y] for x in range(size)]
            for y in range(size)]


def crop(image_path: Path, box: tuple[int, int, int, int]) -> Grid:
    """Returns the pixels of box as rows of RGB tuples."""
    left, top, right, bottom = box
    if right <= left or bottom <= top:
        raise ValueError(f"empty box {box}")
    with Image.open(image_path) as image:
        rgb = image.convert("RGB")
        if left < 0 or top < 0 or right > rgb.width or bottom > rgb.height:
            raise ValueError(f"box {box} outside {image_path.name} ({rgb.width}x{rgb.height})")
        return [[rgb.getpixel((x, y)) for x in range(left, right)] for y in range(top, bottom)]


def _is_title_blue(pixel: Pixel) -> bool:
    r, _, b = pixel
    return b - r > 60


def inactive_title(grid: Grid, first_row: int) -> Grid:
    """Maps the active blue title onto the inactive grey-blue, row by row.

    first_row is the window row of grid[0], so the ramp lands on the right rows.
    """
    out: Grid = []
    for offset, row in enumerate(grid):
        window_row = first_row + offset
        mapped = []
        for pixel in row:
            if pixel in INACTIVE_BY_VALUE:
                mapped.append(INACTIVE_BY_VALUE[pixel])
            elif _is_title_blue(pixel):
                mapped.append(_inactive_row_colour(window_row))
            else:
                mapped.append(pixel)
        out.append(mapped)
    return out


def _inactive_row_colour(window_row: int) -> Pixel:
    if window_row in TITLE_ROW_COLOURS:
        return TITLE_ROW_COLOURS[window_row]
    if window_row in TITLE_RAMP_ROWS:
        step = (window_row - TITLE_RAMP_ROWS.start) * INACTIVE_RAMP_STEP
        return tuple(max(0, c + step) for c in INACTIVE_RAMP_START)  # type: ignore[return-value]
    raise ValueError(f"window row {window_row} is not part of the title")


def _is_dark(pixel: Pixel) -> bool:
    return max(pixel) < DARK_LIMIT


def button_ring(grid: Grid) -> tuple[int, int, int, int] | None:
    """Finds the 13 px outline square of the button in a cell.

    Returns (left, top, right, bottom) of the ring, inclusive. The panel lip
    is a full-height dark column and the inner glyphs are shorter than the
    ring, so only runs close to the button side count.
    """
    height, width = len(grid), len(grid[0])

    def run_lengths(line: list[Pixel]) -> int:
        best = run = 0
        for pixel in line:
            run = run + 1 if _is_dark(pixel) else 0
            best = max(best, run)
        return best

    rows = [y for y in range(height)
            if BUTTON_SIDE - 2 <= run_lengths(grid[y]) <= BUTTON_SIDE + 2]
    cols = [x for x in range(width)
            if BUTTON_SIDE - 2 <= run_lengths([grid[y][x] for y in range(height)])
            <= BUTTON_SIDE + 2]
    if not rows or not cols:
        return None
    return min(cols), min(rows), max(cols), max(rows)


def _map_face(grid: Grid, change) -> Grid:
    ring = button_ring(grid)
    if ring is None:
        raise ValueError("no button outline found in the cell")
    left, top, right, bottom = ring
    out = [list(row) for row in grid]
    for y in range(top + 1, bottom):
        for x in range(left + 1, right):
            out[y][x] = change(out[y][x])
    return out


def pressed(grid: Grid) -> Grid:
    """Armed button: the face inside the outline darkens (Photon's armed fill)."""
    return _map_face(grid, lambda p: tuple(max(0, c + PRESSED_SHIFT) for c in p))


def deactivated(grid: Grid) -> Grid:
    """Unavailable button: the dark glyph pixels turn grey."""
    return _map_face(grid, lambda p: DEACTIVATED_GLYPH if max(p) < 0x70 else p)


def _hex(pixel: Pixel) -> str:
    return "#{:02x}{:02x}{:02x}".format(*pixel)


def svg_for(elements: list[tuple[str, Grid]], extra_ids: tuple[str, ...] = ()) -> str:
    """Stacks each element vertically as a group of 1 px high rect runs."""
    if not elements:
        raise ValueError("no elements")
    gap = 2
    width = max(len(grid[0]) for _, grid in elements)
    parts: list[str] = []
    y0 = 0
    for element, grid in elements:
        parts.append(f'  <g id="{element}">')
        for y, row in enumerate(grid):
            x = 0
            while x < len(row):
                run = 1
                while x + run < len(row) and row[x + run] == row[x]:
                    run += 1
                parts.append(f'    <rect x="{x}" y="{y0 + y}" width="{run}" height="1" '
                             f'fill="{_hex(row[x])}"/>')
                x += run
        parts.append("  </g>")
        y0 += len(grid) + gap
    for element in extra_ids:
        parts.append(f'  <rect id="{element}" x="0" y="{y0}" width="1" height="1" '
                     'fill="#000000" fill-opacity="0"/>')
        y0 += 1 + gap
    header = ('<?xml version="1.0" encoding="UTF-8"?>\n'
              "<!-- This file is part of the qt-classic-styles Project.\n"
              "     License: LGPL-2.1-or-later. Contact: qt-classic-styles-project@trinity2k.net\n"
              "     Generated by make_photon_aurorae.py; edit the generator. -->\n"
              f'<svg xmlns="http://www.w3.org/2000/svg" width="{width}" height="{y0}" '
              f'viewBox="0 0 {width} {y0}">\n')
    return header + "\n".join(parts) + "\n</svg>\n"


_SVG_NS = "{http://www.w3.org/2000/svg}"


def _parse(svg_text: str) -> ET.Element:
    return ET.fromstring(svg_text)  # nosec B314


def element_ids(svg_text: str) -> set[str]:
    return {node.get("id") for node in _parse(svg_text).iter() if node.get("id")}


def read_elements(svg_text: str) -> dict[str, Grid]:
    """Turns the groups of an svg_for() document back into pixel grids."""
    out: dict[str, Grid] = {}
    for group in _parse(svg_text).iter(f"{_SVG_NS}g"):
        rects = [(int(r.get("x")), int(r.get("y")), int(r.get("width")), int(r.get("height")),
                  r.get("fill")) for r in group.iter(f"{_SVG_NS}rect")]
        if not rects:
            continue
        left = min(r[0] for r in rects)
        top = min(r[1] for r in rects)
        right = max(r[0] + r[2] for r in rects)
        bottom = max(r[1] + r[3] for r in rects)
        grid: Grid = [[(0, 0, 0)] * (right - left) for _ in range(bottom - top)]
        for x, y, w, h, fill in rects:
            pixel = (int(fill[1:3], 16), int(fill[3:5], 16), int(fill[5:7], 16))
            for yy in range(y, y + h):
                for xx in range(x, x + w):
                    grid[yy - top][xx - left] = pixel
        out[group.get("id")] = grid
    return out


def write_text_atomic(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with tempfile.NamedTemporaryFile("w", encoding="utf-8", dir=path.parent,
                                     delete=False, suffix=".tmp") as tmp:
        tmp.write(text)
        tmp.flush()
        os.fsync(tmp.fileno())
    # NamedTemporaryFile creates 0600; a theme file gets the usual umask mode.
    umask = os.umask(0)
    os.umask(umask)
    os.chmod(tmp.name, 0o666 & ~umask)
    os.replace(tmp.name, path)


def build_theme(reference_dir: Path, out_dir: Path) -> None:
    """Writes the complete Photon theme folder into out_dir."""
    source = reference_dir / SOURCE
    if not source.is_file():
        raise FileNotFoundError(f"reference screenshot missing: {source}")

    active = [(p.element, repaired(crop(reference_dir / p.source, p.box))) for p in ACTIVE_FRAME]
    grids = dict(active)
    active = [(element, bevel_corner(grids["decoration-right"][0],
                                     [row[0] for row in grids["decoration-bottom"]]))
              if element == "decoration-bottomright" else (element, grid)
              for element, grid in active]
    center = ("decoration-center", [[WINDOW_FILL] * 4 for _ in range(4)])
    title_rows = {"decoration-topleft", "decoration-top", "decoration-topright"}
    inactive = [(element.replace("decoration-", "decoration-inactive-", 1),
                 inactive_title(grid, 0) if element in title_rows else grid)
                for element, grid in active]
    inactive_center = ("decoration-inactive-center", center[1])
    maximized = repaired(crop(reference_dir / MAXIMIZED_TITLE.source, MAXIMIZED_TITLE.box))
    maximized_inactive = inactive_title(maximized, MAXIMIZED_TITLE.box[1])

    decoration = svg_for(
        [*active, center, *inactive, inactive_center,
         ("decoration-maximized-center", maximized),
         ("decoration-maximized-inactive-center", maximized_inactive)],
        extra_ids=("hint-stretch-borders",))
    write_text_atomic(out_dir / "decoration.svg", decoration)

    for piece in BUTTON_CELLS:
        cell = repaired(crop(reference_dir / piece.source, piece.box))
        # The title's blue wraps around the panel's first column at the top
        # and bottom, so inactive windows need the inactive title there too.
        inactive_cell = inactive_title(cell, piece.box[1])
        write_text_atomic(out_dir / f"{piece.element}.svg",
                          svg_for([("active-center", cell),
                                   ("pressed-center", pressed(cell)),
                                   ("deactivated-center", deactivated(cell)),
                                   ("inactive-center", inactive_cell),
                                   ("pressed-inactive-center", pressed(inactive_cell)),
                                   ("deactivated-inactive-center", deactivated(inactive_cell))]))

    write_text_atomic(out_dir / f"{THEME_NAME}rc", RC_TEXT)
    write_text_atomic(out_dir / "metadata.desktop", METADATA_TEXT)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Generate the Photon Aurorae theme.")
    default_reference = Path(__file__).resolve().parents[3] / "reference" / "qnx-photon"
    parser.add_argument("--reference", type=Path, default=default_reference,
                        help="folder with qnx621fileman.png (default: the repo's reference)")
    parser.add_argument("--out", type=Path, required=True,
                        help="theme folder to write, named Photon")
    args = parser.parse_args(argv)
    if args.out.name != THEME_NAME:
        parser.error(f"the theme folder must be named {THEME_NAME} (KWin matches it to {THEME_NAME}rc)")
    build_theme(args.reference, args.out)
    print(f"wrote {args.out}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
